### ISSUE TITLE
Send key value with the messages

### ISSUE THREAD

**Issue by Hiteshkikani** [GSLabDev/pepper-box#10]
Hi,
I am trying to implement a test in which message should be sent with the key to kafka, so that when i consume the message (sent by jmeter) from kafka, i can see something like this:
[2018-02-20 08:47:45,206] INFO Message consumed: ConsumerRecord(topic = test, partition = 0, offset = 3437, CreateTime = 1519109958252, checksum = 1094544467, serialized key size = 82, serialized value size = 255, key = {"this is key"}, value = {"this is test message}})(com.messagehub.samples.ConsumerRunnable)

currently without key, i can see this:
[2018-02-20 09:23:50,700] INFO Message consumed: ConsumerRecord(topic = test, partition = 0, offset = 3542, CreateTime = 1519111430376, checksum = 3574368010, serialized key size = -1, serialized value size = 4499, key = null, value = {"this is test message}})(com.messagehub.samples.ConsumerRunnable)

I am not expert in kafka, so i am not sure if we already have such functionalities in pepper-box plugin and might be i just don't know how to use those features.

Thanks in advance.

Br,
Hitesh

**Comment by satishbhor** [comment]
Are u looking for static key or dynamic key based messages ?

**Comment by Hiteshkikani** [comment]
In my case, key would be different everytime message is sent to kafka, so yes I am looking for dynamics key based messages.

**Comment by Nachiket90** [comment]
Earlier we never faced such usecase but this looks useful and we will provide solution to this soon. Thanks.

**Comment by Hiteshkikani** [comment]
That would be great! Thanks.

**Comment by satishbhor** [comment]
@Hiteshkikani  @Nachiket90 has pushed fix for this, In sampler config `keyed.message` is set to `NO` by default, you can set it to `YES`.  If its `YES` then it will  pick value of `message.key.placeholder` its JMETER variable name to which you can set dynamic values.

**Comment by Hiteshkikani** [comment]
Super!! This works like a charm. Thanks a lot. I will close the issue.

**Comment by ogulcanarbc** [comment]
Can you update the readme.md file so we can see it as an example? @satishbhor

**Comment by NaliniSake** [comment]
Hi, Could someone please help me on below issue. Really appreciate!
I attached the avro schema in 'Message placeholder key' of pepepr-box plain text as shown below and parse the 'Message key placeholder value' in peper-box sampler. I gave the 'Value'  in 'message.value.placeholder' which needs to be post to the topic along with schema. But here, encountered with error "ERROR c.g.p.s.PepperBoxKafkaSampler: Failed to send message"
![image](https://user-images.githubusercontent.com/98602032/152267718-3248a319-ea03-4a45-bad5-957ffa51e969.png)
![image](https://user-images.githubusercontent.com/98602032/152277396-758cc5ea-2bdf-4a59-9dac-4ce95bcb2398.png)
