### ISSUE TITLE
The plugin does not work on windows (10) - jmeter-3.3, pepper-box-1.0

### ISSUE THREAD

**Issue by aladevr** [GSLabDev/pepper-box#14]
If you are trying to send a message from windows, then you get the following error:
https://uploads.disquscdn.com/images/3cdd263a0af90bd3afe50c422ae44f701f42bca29cb52bc2b3540c33c8718926.png
But If you are trying to send a message from ubuntu (14), everything is ok.

**Comment by satishbhor** [comment]
Thats JRE issue windows comes with default JRE, Papper-box requirement is JDK hence remove JRE from windows path and try again it should work
