### ISSUE TITLE
mvn build failure 

### ISSUE THREAD

**Issue by anmolsurmountsoft** [GSLabDev/pepper-box#15]
I haven jmeter version 3.1 and kafka verson 0.11.0 

when i try to build project using 

` mvn clean install -Djmeter.version=3.1 -Dkafka.version=0.11.0.0`

there is build failure 

`[INFO] Scanning for projects...
[WARNING] 
[WARNING] Some problems were encountered while building the effective model for pepper-box:pepper-box:jar:1.0
[WARNING] 'dependencies.dependency.(groupId:artifactId:type:classifier)' must be unique: org.apache.kafka:kafka_2.11:jar -> duplicate declaration of version ${kafka.version} @ line 54, column 17
[WARNING] 
[WARNING] It is highly recommended to fix these problems because they threaten the stability of your build.
[WARNING] 
[WARNING] For this reason, future Maven versions might no longer support building such malformed projects.
[WARNING] 
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building pepper-box 1.0
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ pepper-box ---
[INFO] 
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ pepper-box ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 6 resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.6.0:compile (default-compile) @ pepper-box ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 26 source files to /home/anmol/pepper-box/target/classes
[INFO] /home/anmol/pepper-box/src/main/java/com/gslab/pepper/loadgen/impl/PlaintTextLoadGenerator.java: Some input files use unchecked or unsafe operations.
[INFO] /home/anmol/pepper-box/src/main/java/com/gslab/pepper/loadgen/impl/PlaintTextLoadGenerator.java: Recompile with -Xlint:unchecked for details.
[INFO] 
[INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ pepper-box ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /home/anmol/pepper-box/src/test/resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.6.0:testCompile (default-testCompile) @ pepper-box ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 7 source files to /home/anmol/pepper-box/target/test-classes
[INFO] -------------------------------------------------------------
[ERROR] COMPILATION ERROR : 
[INFO] -------------------------------------------------------------
[ERROR] /home/anmol/pepper-box/src/test/java/com/gslab/pepper/test/PepperBoxSamplerTest.java:[65,9] cannot find symbol
  symbol:   class Time
  location: class com.gslab.pepper.test.PepperBoxSamplerTest
[ERROR] /home/anmol/pepper-box/src/test/java/com/gslab/pepper/test/PepperBoxLoadGenTest.java:[59,9] cannot find symbol
  symbol:   class Time
  location: class com.gslab.pepper.test.PepperBoxLoadGenTest
[INFO] 2 errors 
[INFO] -------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 4.103 s
[INFO] Finished at: 2018-03-01T13:00:57+05:30
[INFO] Final Memory: 36M/347M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.6.0:testCompile (default-testCompile) on project pepper-box: Compilation failure: Compilation failure:
[ERROR] /home/anmol/pepper-box/src/test/java/com/gslab/pepper/test/PepperBoxSamplerTest.java:[65,9] cannot find symbol
[ERROR] symbol:   class Time
[ERROR] location: class com.gslab.pepper.test.PepperBoxSamplerTest
[ERROR] /home/anmol/pepper-box/src/test/java/com/gslab/pepper/test/PepperBoxLoadGenTest.java:[59,9] cannot find symbol
[ERROR] symbol:   class Time
[ERROR] location: class com.gslab.pepper.test.PepperBoxLoadGenTest
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
`

can you help me with this

**Comment by satishbhor** [comment]
Pushed new branch try it out ` jmeter3.2_kafka0.11.0.0 `

**Comment by anmolsurmountsoft** [comment]
@satishbhor  build is success but still there are 13 test fails  and warning 

` Some problems were encountered while building the effective model for pepper-box:pepper-box:jar:1.0 [WARNING] 'dependencies.dependency.(groupId:artifactId:type:classifier)' must be unique: org.apache.kafka:kafka_2.11:jar -> duplicate declaration of version ${kafka.version} ` 

still continues

**Comment by satishbhor** [comment]
@anmolsurmountsoft Thanks I have removed duplicate dependencies, but I believe all test cases are passing.
[pepperbox.log](https://github.com/GSLabDev/pepper-box/files/1771079/pepperbox.log)

**Comment by anmolsurmountsoft** [comment]
@satishbhor now getting this error 
i am running with  this command 
`mvn clean install -Djmeter.version=3.2 -Dkafka.version=0.11.0.0`

`
[INFO] Scanning for projects...
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building pepper-box 1.0
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ pepper-box ---
[INFO] Deleting /home/anmol/pepper-box/target
[INFO] 
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ pepper-box ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 6 resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.6.0:compile (default-compile) @ pepper-box ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 26 source files to /home/anmol/pepper-box/target/classes
[WARNING] /home/anmol/pepper-box/src/main/java/com/gslab/pepper/config/serialized/SerializedConfigElementBeanInfo.java:[9,34] org.apache.jorphan.logging.LoggingManager in org.apache.jorphan.logging has been deprecated
[WARNING] /home/anmol/pepper-box/src/main/java/com/gslab/pepper/config/serialized/SerializedConfigElementBeanInfo.java:[10,22] org.apache.log.Logger in org.apache.log has been deprecated
[WARNING] /home/anmol/pepper-box/src/main/java/com/gslab/pepper/loadgen/impl/PlaintTextLoadGenerator.java:[6,34] org.apache.jorphan.logging.LoggingManager in org.apache.jorphan.logging has been deprecated
[WARNING] /home/anmol/pepper-box/src/main/java/com/gslab/pepper/loadgen/impl/PlaintTextLoadGenerator.java:[7,22] org.apache.log.Logger in org.apache.log has been deprecated
[WARNING] /home/anmol/pepper-box/src/main/java/com/gslab/pepper/sampler/PepperBoxKafkaSampler.java:[13,34] org.apache.jorphan.logging.LoggingManager in org.apache.jorphan.logging has been deprecated
[WARNING] /home/anmol/pepper-box/src/main/java/com/gslab/pepper/sampler/PepperBoxKafkaSampler.java:[20,22] org.apache.log.Logger in org.apache.log has been deprecated
[WARNING] /home/anmol/pepper-box/src/main/java/com/gslab/pepper/config/plaintext/PlainTextConfigElement.java:[13,34] org.apache.jorphan.logging.LoggingManager in org.apache.jorphan.logging has been deprecated
[WARNING] /home/anmol/pepper-box/src/main/java/com/gslab/pepper/config/plaintext/PlainTextConfigElement.java:[14,22] org.apache.log.Logger in org.apache.log has been deprecated
[WARNING] /home/anmol/pepper-box/src/main/java/com/gslab/pepper/loadgen/impl/SerializedLoadGenerator.java:[7,34] org.apache.jorphan.logging.LoggingManager in org.apache.jorphan.logging has been deprecated
[WARNING] /home/anmol/pepper-box/src/main/java/com/gslab/pepper/loadgen/impl/SerializedLoadGenerator.java:[8,22] org.apache.log.Logger in org.apache.log has been deprecated
[WARNING] /home/anmol/pepper-box/src/main/java/com/gslab/pepper/config/serialized/SerializedConfigElement.java:[13,34] org.apache.jorphan.logging.LoggingManager in org.apache.jorphan.logging has been deprecated
[WARNING] /home/anmol/pepper-box/src/main/java/com/gslab/pepper/config/serialized/SerializedConfigElement.java:[14,22] org.apache.log.Logger in org.apache.log has been deprecated
[WARNING] /home/anmol/pepper-box/src/main/java/com/gslab/pepper/config/serialized/SerializedConfigElementBeanInfo.java:[9,34] org.apache.jorphan.logging.LoggingManager in org.apache.jorphan.logging has been deprecated
[WARNING] /home/anmol/pepper-box/src/main/java/com/gslab/pepper/config/serialized/SerializedConfigElementBeanInfo.java:[10,22] org.apache.log.Logger in org.apache.log has been deprecated
[WARNING] /home/anmol/pepper-box/src/main/java/com/gslab/pepper/loadgen/impl/PlaintTextLoadGenerator.java:[6,34] org.apache.jorphan.logging.LoggingManager in org.apache.jorphan.logging has been deprecated
[WARNING] /home/anmol/pepper-box/src/main/java/com/gslab/pepper/loadgen/impl/PlaintTextLoadGenerator.java:[7,22] org.apache.log.Logger in org.apache.log has been deprecated
[WARNING] /home/anmol/pepper-box/src/main/java/com/gslab/pepper/sampler/PepperBoxKafkaSampler.java:[13,34] org.apache.jorphan.logging.LoggingManager in org.apache.jorphan.logging has been deprecated
[WARNING] /home/anmol/pepper-box/src/main/java/com/gslab/pepper/sampler/PepperBoxKafkaSampler.java:[20,22] org.apache.log.Logger in org.apache.log has been deprecated
[WARNING] /home/anmol/pepper-box/src/main/java/com/gslab/pepper/config/plaintext/PlainTextConfigElement.java:[13,34] org.apache.jorphan.logging.LoggingManager in org.apache.jorphan.logging has been deprecated
[WARNING] /home/anmol/pepper-box/src/main/java/com/gslab/pepper/config/plaintext/PlainTextConfigElement.java:[14,22] org.apache.log.Logger in org.apache.log has been deprecated
[WARNING] /home/anmol/pepper-box/src/main/java/com/gslab/pepper/loadgen/impl/SerializedLoadGenerator.java:[7,34] org.apache.jorphan.logging.LoggingManager in org.apache.jorphan.logging has been deprecated
[WARNING] /home/anmol/pepper-box/src/main/java/com/gslab/pepper/loadgen/impl/SerializedLoadGenerator.java:[8,22] org.apache.log.Logger in org.apache.log has been deprecated
[WARNING] /home/anmol/pepper-box/src/main/java/com/gslab/pepper/config/serialized/SerializedConfigElement.java:[13,34] org.apache.jorphan.logging.LoggingManager in org.apache.jorphan.logging has been deprecated
[WARNING] /home/anmol/pepper-box/src/main/java/com/gslab/pepper/config/serialized/SerializedConfigElement.java:[14,22] org.apache.log.Logger in org.apache.log has been deprecated
[WARNING] /home/anmol/pepper-box/src/main/java/com/gslab/pepper/config/serialized/SerializedConfigElementBeanInfo.java:[9,34] org.apache.jorphan.logging.LoggingManager in org.apache.jorphan.logging has been deprecated
[WARNING] /home/anmol/pepper-box/src/main/java/com/gslab/pepper/config/serialized/SerializedConfigElementBeanInfo.java:[10,22] org.apache.log.Logger in org.apache.log has been deprecated
[WARNING] /home/anmol/pepper-box/src/main/java/com/gslab/pepper/loadgen/impl/PlaintTextLoadGenerator.java:[6,34] org.apache.jorphan.logging.LoggingManager in org.apache.jorphan.logging has been deprecated
[WARNING] /home/anmol/pepper-box/src/main/java/com/gslab/pepper/loadgen/impl/PlaintTextLoadGenerator.java:[7,22] org.apache.log.Logger in org.apache.log has been deprecated
[WARNING] /home/anmol/pepper-box/src/main/java/com/gslab/pepper/sampler/PepperBoxKafkaSampler.java:[13,34] org.apache.jorphan.logging.LoggingManager in org.apache.jorphan.logging has been deprecated
[WARNING] /home/anmol/pepper-box/src/main/java/com/gslab/pepper/sampler/PepperBoxKafkaSampler.java:[20,22] org.apache.log.Logger in org.apache.log has been deprecated
[WARNING] /home/anmol/pepper-box/src/main/java/com/gslab/pepper/config/plaintext/PlainTextConfigElement.java:[13,34] org.apache.jorphan.logging.LoggingManager in org.apache.jorphan.logging has been deprecated
[WARNING] /home/anmol/pepper-box/src/main/java/com/gslab/pepper/config/plaintext/PlainTextConfigElement.java:[14,22] org.apache.log.Logger in org.apache.log has been deprecated
[WARNING] /home/anmol/pepper-box/src/main/java/com/gslab/pepper/loadgen/impl/SerializedLoadGenerator.java:[7,34] org.apache.jorphan.logging.LoggingManager in org.apache.jorphan.logging has been deprecated
[WARNING] /home/anmol/pepper-box/src/main/java/com/gslab/pepper/loadgen/impl/SerializedLoadGenerator.java:[8,22] org.apache.log.Logger in org.apache.log has been deprecated
[WARNING] /home/anmol/pepper-box/src/main/java/com/gslab/pepper/config/serialized/SerializedConfigElement.java:[13,34] org.apache.jorphan.logging.LoggingManager in org.apache.jorphan.logging has been deprecated
[WARNING] /home/anmol/pepper-box/src/main/java/com/gslab/pepper/config/serialized/SerializedConfigElement.java:[14,22] org.apache.log.Logger in org.apache.log has been deprecated
[WARNING] /home/anmol/pepper-box/src/main/java/com/gslab/pepper/loadgen/impl/PlaintTextLoadGenerator.java:[25,26] org.apache.log.Logger in org.apache.log has been deprecated
[WARNING] /home/anmol/pepper-box/src/main/java/com/gslab/pepper/loadgen/impl/PlaintTextLoadGenerator.java:[25,39] org.apache.jorphan.logging.LoggingManager in org.apache.jorphan.logging has been deprecated
[WARNING] /home/anmol/pepper-box/src/main/java/com/gslab/pepper/sampler/PepperBoxKafkaSampler.java:[50,26] org.apache.log.Logger in org.apache.log has been deprecated
[WARNING] /home/anmol/pepper-box/src/main/java/com/gslab/pepper/sampler/PepperBoxKafkaSampler.java:[50,39] org.apache.jorphan.logging.LoggingManager in org.apache.jorphan.logging has been deprecated
[WARNING] /home/anmol/pepper-box/src/main/java/com/gslab/pepper/config/plaintext/PlainTextConfigElement.java:[27,26] org.apache.log.Logger in org.apache.log has been deprecated
[WARNING] /home/anmol/pepper-box/src/main/java/com/gslab/pepper/config/plaintext/PlainTextConfigElement.java:[27,39] org.apache.jorphan.logging.LoggingManager in org.apache.jorphan.logging has been deprecated
[WARNING] /home/anmol/pepper-box/src/main/java/com/gslab/pepper/loadgen/impl/SerializedLoadGenerator.java:[26,26] org.apache.log.Logger in org.apache.log has been deprecated
[WARNING] /home/anmol/pepper-box/src/main/java/com/gslab/pepper/loadgen/impl/SerializedLoadGenerator.java:[26,39] org.apache.jorphan.logging.LoggingManager in org.apache.jorphan.logging has been deprecated
[WARNING] /home/anmol/pepper-box/src/main/java/com/gslab/pepper/config/serialized/SerializedConfigElement.java:[88,26] org.apache.log.Logger in org.apache.log has been deprecated
[WARNING] /home/anmol/pepper-box/src/main/java/com/gslab/pepper/config/serialized/SerializedConfigElement.java:[88,39] org.apache.jorphan.logging.LoggingManager in org.apache.jorphan.logging has been deprecated
[INFO] /home/anmol/pepper-box/src/main/java/com/gslab/pepper/loadgen/impl/PlaintTextLoadGenerator.java: Some input files use unchecked or unsafe operations.
[INFO] /home/anmol/pepper-box/src/main/java/com/gslab/pepper/loadgen/impl/PlaintTextLoadGenerator.java: Recompile with -Xlint:unchecked for details.
[INFO] 
[INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ pepper-box ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /home/anmol/pepper-box/src/test/resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.6.0:testCompile (default-testCompile) @ pepper-box ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 7 source files to /home/anmol/pepper-box/target/test-classes
[INFO] -------------------------------------------------------------
[ERROR] COMPILATION ERROR : 
[INFO] -------------------------------------------------------------
[ERROR] /home/anmol/pepper-box/src/test/java/com/gslab/pepper/test/PepperBoxSamplerTest.java:[65,9] cannot find symbol
  symbol:   class Time
  location: class com.gslab.pepper.test.PepperBoxSamplerTest
[ERROR] /home/anmol/pepper-box/src/test/java/com/gslab/pepper/test/PepperBoxLoadGenTest.java:[59,9] cannot find symbol
  symbol:   class Time
  location: class com.gslab.pepper.test.PepperBoxLoadGenTest
[INFO] 2 errors 
[INFO] -------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 5.190 s
[INFO] Finished at: 2018-03-01T21:51:34+05:30
[INFO] Final Memory: 37M/383M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.6.0:testCompile (default-testCompile) on project pepper-box: Compilation failure: Compilation failure:
[ERROR] /home/anmol/pepper-box/src/test/java/com/gslab/pepper/test/PepperBoxSamplerTest.java:[65,9] cannot find symbol
[ERROR] symbol:   class Time
[ERROR] location: class com.gslab.pepper.test.PepperBoxSamplerTest
[ERROR] /home/anmol/pepper-box/src/test/java/com/gslab/pepper/test/PepperBoxLoadGenTest.java:[59,9] cannot find symbol
[ERROR] symbol:   class Time
[ERROR] location: class com.gslab.pepper.test.PepperBoxLoadGenTest
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException

`

**Comment by satishbhor** [comment]
@anmolsurmountsoft hope u r pulling `jmeter3.2_kafka0.11.0.0` branch

**Comment by anmolsurmountsoft** [comment]
@satishbhor  thanks a lot :)

**Comment by sfc-gh-japatel** [comment]
If anyone encounters issue with correct branch mentioned here and right command. Make sure you are using openjdk 8. 
```
which java
/Library/Java/JavaVirtualMachines/openjdk-8.jdk/Contents/Home/bin/java

git checkout origin/jmeter3.2_kafka0.11.0.0 -b jmeter3.2_kafka0.11.0.0

mvn clean install -Djmeter.version=3.2 -Dkafka.version=0.11.0.0
```
