### ISSUE TITLE
Where's is the keyed message feature?

### ISSUE THREAD

**Issue by MasterMartbob** [GSLabDev/pepper-box#17]
I don't know what Im doing wrong but I can't see the keyed message feature.

Here the step I did.

git clone https://github.com/GSLabDev/pepper-box.git
cd pepper-box/
mvn clean install -Djmeter.version=3.0 -Dkafka.version=0.9.0.1

Build Success
I copy the ./target/pepper-box-1.0.jar in JMETER_HOME/lib/ext/

I start Jmeter add a Sampler Java Request choose PepperBox as classname.
Now I don't see the propertie of keyed.message

Here is the properties I see.
`

bootstrap.servers |  
-- | --
zookeeper.servers |  
kafka.topic.name |  
key.serializer | org.apache.kafka.common.serialization.StringSerializer
value.serializer | org.apache.kafka.common.serialization.StringSerializer
compression.type | none
batch.size | 16384
linger.ms | 0
buffer.memory | 33554432
acks | 1
send.buffer.bytes | 131072
receive.buffer.bytes | 32768
security.protocol | PLAINTEXT
message.placeholder.key | MESSAGE
kerberos.auth.enabled | NO
java.security.auth.login.config |  
java.security.krb5.conf |  
sasl.kerberos.service.name | kafka
sasl.mechanism | GSSAPI
ssl.enabled | NO
ssl.key.password |  
ssl.keystore.location |  
ssl.keystore.password |  
ssl.truststore.location |  
ssl.truststore.password |  

`
I tried with Jmeter 3.0 and 3.3

From this issue I was sure it was in the main branch. 
https://github.com/GSLabDev/pepper-box/issues/10

**Comment by satishbhor** [comment]
![jmeter](https://user-images.githubusercontent.com/538910/37796811-2f1f78b0-2e3e-11e8-964f-78574b005b9b.png)

**Comment by satishbhor** [comment]
Are you using latest code ?

**Comment by MasterMartbob** [comment]
I was assuming so since I just did a 
git clone https://github.com/GSLabDev/pepper-box.git
yesteday.
The code seams there I looked at the fix and the files are there with the fix.
Is there some sort of cache in Jmeter I tried a new install but still the same problem.

I assume the build or jmeter is messing with me.

**Comment by MasterMartbob** [comment]
There you go.

[pepper-box-04-05-2018.tar.gz](https://github.com/GSLabDev/pepper-box/files/1881126/pepper-box-04-05-2018.tar.gz)

**Comment by MasterMartbob** [comment]
Today I did the step again to make the tar.gz you asked for, because I lost my previous clone.
I tried it and now I see the keyed.message property.
I don't know if it's me or the new git clone but it seams to work now.

Thanks
