### ISSUE TITLE
Facing Error with Plugin - "Failed to create PlaintTextLoadGenerator instance"

### ISSUE THREAD

**Issue by ganeshmuralidhar** [GSLabDev/pepper-box#20]
Hi team,

I tried to add this plugin and followed the exact process referred on GIT. I am seeing an error when trying to trigger the test. Attached are my configuration snapshots and jmeter log with error.

I also tried the same with sample JMX given in the repo and observed the same error. While i tried with a custom template, i also tried with plain text and other formats which did not work.

Can you please help me here?

![image](https://user-images.githubusercontent.com/29456270/38308554-22155af8-3835-11e8-84d1-5e78f080bbee.png)
![image](https://user-images.githubusercontent.com/29456270/38308558-25bb62ba-3835-11e8-882a-f8fc62eea61e.png)
[jmeterLog.txt](https://github.com/GSLabDev/pepper-box/files/1875758/jmeterLog.txt)

**Comment by saikris12** [comment]
Same issue for me as well.

**Comment by ganeshmuralidhar** [comment]
@Nachiket90 - The plugin seems to be deleting my entry when i try to save the Java request sampler with these new options!!!! However, just want to add that even before the Java request sampler is initiated, my PlainTextConfig itself is failing to start. And I tried this on Jmeter 3.0 and 3.3. I have JDK home and Java Home already set to proper locations. Still i am not able to execute a sample. Can you please assist?

![image](https://user-images.githubusercontent.com/29456270/38348594-704a3244-38c0-11e8-91f9-d6588f4bcdac.png)

**Comment by satishbhor** [comment]
@ganeshmuralidhar by looking at logs u shared, ur jmeter is picking up java from JRE and not from JDK

**Comment by ganeshmuralidhar** [comment]
Ok - But my where javac shows JDK path! 

![image](https://user-images.githubusercontent.com/29456270/38350542-583fd862-38c9-11e8-962a-42628c7bb0e3.png)

**Comment by ganeshmuralidhar** [comment]
Sorted this in a very simple way! I am not using the PlainTextConfig and started using JSR223 sampler with below code. Continued to use the Pepper-Box Javarequest Sampler with all default options available. Successfully able to post the messages to Kafka

![image](https://user-images.githubusercontent.com/29456270/38414268-a676549c-39ab-11e8-899b-21c8f57c6650.png)
![image](https://user-images.githubusercontent.com/29456270/38414277-adf0b3ca-39ab-11e8-8994-0efeddfec0d4.png)

**Comment by satishbhor** [comment]
@ganeshmuralidhar can u do one thing when u launch Jmeter can u trace which java command it picks

**Comment by ganeshmuralidhar** [comment]
Can you elaborate on how to capture that? @satishbhor

**Comment by Nachiket90** [comment]
Check JDK path from windows task manager process. Click on Jmeter process -> properties -> general tab should show you JDK path used. Here is screenshot for reference.

![jmeter](https://user-images.githubusercontent.com/6228374/38415301-ba160166-39ae-11e8-906e-84a08da65f08.png)

**Comment by ganeshmuralidhar** [comment]
@Nachiket90 This shows me a JRE path.. @satishbhor also pointed this, but i couldn't find a way to change it back to JDK. Hence I had to try a work around for this and use JSR223 sampler.

![image](https://user-images.githubusercontent.com/29456270/38415539-71b0aed4-39af-11e8-8118-0dee4e9c8251.png)

**Comment by satishbhor** [comment]
Thats the issue :)

**Comment by ganeshmuralidhar** [comment]
My environment variables do have an entry for JRE but a JDK entry is before that.. and that should ideally be picked as Env vars are traversed sequentially to pick the relavant process. Are you saying that I should try removing JRE entries completely out?

**Comment by satishbhor** [comment]
yes

**Comment by Nachiket90** [comment]
Or specifically set JM_LAUNCH variable to <JDK path>/bin/java.exe in jmeter.bat file.

**Comment by ganeshmuralidhar** [comment]
Awesome! This works now with the JM_LAUNCH set in the jmeter.bat file!!!
