### ISSUE TITLE
Push compiled JARs to maven central repo?

### ISSUE THREAD

**Issue by daluu** [GSLabDev/pepper-box#27]
Is it expected that users will have to compile the JAR themselves or find a precompiled JAR somewhere like https://github.com/raladev/load/blob/master/JARs/pepper-box-1.0.jar?

Like https://github.com/BrightTag/kafkameter/issues/10, it would be nice if users could just pull from maven if they don't need latest & greatest or need to do their own customizations.

btw, came across this project from https://www.blazemeter.com/blog/apache-kafka-how-to-load-test-with-jmeter

**Comment by Nachiket90** [comment]
Hi @daluu, currently compiling the jar is the only way and we are working on putting it in maven central.
Thanks for your suggestions.
