### ISSUE TITLE
Kafka Version 0.10.0.1 supported?

### ISSUE THREAD

**Issue by wesleychipecoIDS** [GSLabDev/pepper-box#36]
Hello,

The Kafka service I am using pepper-box to test has been upgraded to 0.10.0.1 and the plugin is not working anymore. Can anyone confirm that 0.10.0.1 is not supported and if there are any plans for this support?

**Comment by Nachiket90** [comment]
Hi,

Yes. this version is supported. You can try with kafka0.10.2 branch.
