### ISSUE TITLE
PlainText Config Templates with functions fail JSONLint validation

### ISSUE THREAD

**Issue by BILJ65** [GSLabDev/pepper-box#39]
I like to validate my JSON first with jsonlint.com but when it contains functions that have quoted parameters (like SEQUENCE) it fails validation.  For example, 
"messageId":{{SEQUENCE("messageId", 1, 1)}}
fails because the braces are reserved characters in JSON and confuse the validator.
If i try to quote the value, like
"messageId":"{{SEQUENCE("messageId", 1, 1)}}"
it also fails because it thinks the quotes are being closed at the wrong point.
I've tried escaping the double quotes around "messageId", and I've tried escaping the braces, but nothing works.
Is it possible to have functions support single quotes around the parameters?

**Comment by Nachiket90** [comment]
Unfortunately current structure is using double quotes around the parameters but PR supporting single quotes is welome :)
