### ISSUE TITLE
SSL Authentication not supported

### ISSUE THREAD

**Issue by MasterMartbob** [GSLabDev/pepper-box#7]
It's specified in the doc we can add parameters to the PepperBoxKafka Sampler by using "_" like so:

_ssl.key.password
_ssl.keystore.location
_ssl.keystore.password
_ssl.truststore.location
_ssl.truststore.password

But when I add parameters to the java request they keep disappearing and it seams those are not working for some reason.(https://stackoverflow.com/questions/40307641/jmeter-doesnt-save-parameter-for-java-request) 

So how do I add those parameters ?

**Comment by satishbhor** [comment]
Thanks for using Pepper-Box, we will add patch to support SSL values in a day.

**Comment by satishbhor** [comment]
@MasterMartbob committed code against this issue, you can take pull and use it.

**Comment by satishbhor** [comment]
@MasterMartbob if you are satisfied with issue, could you please close it?

**Comment by allenlai18** [comment]
@satishbhor This issue is still happening for me. Is it pushed to master

**Comment by mattiamatrix** [comment]
@allenlai18 I can confirm that SSL Authentication is working, buggy, but it is working.

For example, one problem is that throws Exceptions if the Keystore path is not provided even if it's not required (I'm using only the Truststore).

**Comment by kenkeustermans** [comment]
How can you add the parameters to the java request? 
_ssl.key.password
_ssl.keystore.location
_ssl.keystore.password
_ssl.truststore.location
_ssl.truststore.password
